version: '3'
services:
  backend:
    build: ./backend
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./backend/volumes:/app/volumes
  
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend